RUNBOOKS = (
    {
        "id": "k8s-pod-troubleshooting",
        "title": "Kubernetes Pod Troubleshooting",
        "keywords": (
            "kubernetes",
            "pod",
            "imagepullbackoff",
            "errimagepull",
            "crashloopbackoff",
            "aks",
        ),
        "steps": (
            "kubectl get pod -n <namespace> -o wide",
            "kubectl describe pod <pod> -n <namespace>",
            "kubectl logs <pod> -n <namespace> --all-containers=true",
            "依 Events / logs 判斷 image、probe、resource、volume 或 network 問題。",
        ),
    },
    {
        "id": "database-connectivity",
        "title": "Database Connectivity Troubleshooting",
        "keywords": (
            "database",
            "postgresql",
            "vertica",
            "oracle",
            "connection refused",
            "timeout",
            "jdbc",
        ),
        "steps": (
            "確認 hostname、port、database/service name 與 credential source。",
            "從應用程式所在主機或 Pod 測試 DNS 與 TCP connectivity。",
            "確認 DB listener、pg_hba/firewall/ACL 與 connection limit。",
            "比對近期帳密、憑證、DNS 或 network policy 變更。",
        ),
    },
    {
        "id": "etl-failure-triage",
        "title": "ETL / Pipeline Failure Triage",
        "keywords": (
            "etl",
            "airflow",
            "hop",
            "pipeline",
            "dag",
            "task failed",
            "job failed",
        ),
        "steps": (
            "鎖定第一個失敗 task/job 與 execution id。",
            "確認 upstream input、row count、參數、credential 與外部 dependency。",
            "比對最近一次成功執行與近期 code/config deployment。",
            "若要重跑，先確認 idempotency 與重複寫入風險。",
        ),
    },
    {
        "id": "storage-permission",
        "title": "Mounted Storage Permission Troubleshooting",
        "keywords": (
            "permission denied",
            "nfs",
            "azure file",
            "volume",
            "mount",
            "fsGroup",
        ),
        "steps": (
            "確認 mount point、mount options 與 server-side export/share 權限。",
            "確認 process UID/GID 與檔案 owner/group。",
            "Kubernetes 環境檢查 securityContext、runAsUser、runAsGroup、fsGroup。",
            "先以非破壞方式測試 read/write，不直接刪除既有檔案。",
        ),
    },
)
